import { MessageSquare, CalendarDays, ListTodo, ArrowUpRight, ChevronRight, Bot, Plug, Plus } from 'lucide-react';
import { useStore } from './store';
import { TODAY } from './data';
import { Button, Badge, BookingRows, Avatar } from './components';
export default function Home({ navigate, onEdit, onNew, openChat }) {
  const { workspace: w, template } = useStore();
  const rows = w.bookings.filter(b => b.date === TODAY && b.status !== '已取消').sort((a,b) => a.time.localeCompare(b.time));
  const pending = w.conversations.filter(c => c.mode === 'pending' && !c.resolved);
  const date = new Date(`${TODAY}T12:00:00`).toLocaleDateString('zh-CN', { month: 'long', day: 'numeric', weekday: 'long' });
  return <><div className="page-heading"><div><h1>下午好，{w.shop.owner}<span className="greeting-dot">.</span></h1><p>把日常交给助手，把时间留给生意。</p></div><Button variant="primary" onClick={onNew}><Plus size={18}/>新增{template.noun}</Button></div>
    <div className="metrics">{[{ label:'今日咨询', value:w.conversations.filter(c => c.date === TODAY).length, icon:MessageSquare, tone:'blue', hint:'每一次对话，都是新机会', action:() => navigate('messages') }, { label:`今日${template.noun}`,value:rows.length,icon:CalendarDays,tone:'green',hint:`${rows.filter(b => b.status === '已确认').length} 条已确认，按计划进行`,action:() => navigate('bookings') },{ label:'待处理',value:pending.length,icon:ListTodo,tone:'amber',hint:pending.length ? '有客户正在等待你的帮助' : '一切都已处理妥当',action:() => navigate('messages') }].map(m => <button key={m.label} className="metric" onClick={m.action}><span className={`metric-icon ${m.tone}`}><m.icon size={23}/></span><span><span className="metric-label">{m.label}</span><strong>{m.value}</strong><small>{m.hint}</small></span><ArrowUpRight size={16} className="metric-arrow"/></button>)}</div>
    <div className="home-grid"><section className="panel schedule-panel"><div className="section-heading"><div><h2>今天的安排</h2><p>{date}</p></div><Button variant="text" onClick={() => navigate('bookings')}>查看全部<ChevronRight size={15}/></Button></div><BookingRows bookings={rows} onEdit={onEdit}/><div className="schedule-note"><CalendarDays size={15}/>让每位客户，都被好好记住。</div></section><div className="home-right"><section className="panel attention"><div className="section-heading"><h2>需要你看一下</h2><span className="count">{pending.length}</span></div>{pending.length ? pending.map((chat, i) => { const c = w.customers.find(x => x.id === chat.customerId); return <div className="attention-item" key={chat.id}><div className="inline"><Avatar name={c.name} index={i + 1}/><div className="grow"><strong>{c.name}</strong><small>等待人工处理</small></div><span className="subtle small">{chat.messages.at(-1).time}</span></div><p>{chat.messages.find(m => m.from === 'customer').text}</p><button className="text-link" onClick={() => openChat(chat.id)}>查看对话<ArrowUpRight size={15}/></button></div>; }) : <div className="calm-empty">全部处理好了，给自己松口气。</div>}</section><section className="panel assistant-status"><div className="section-heading"><div className="inline"><Bot size={21}/><h2>AI 助手</h2></div><Badge tone="green">演示运行</Badge></div><p>你的店铺助手，随时准备好。</p><div className="connection-row"><span className="inline"><Plug size={17}/>WhatsApp</span><span className="subtle small"><i className="status-dot gray"/>未连接</span></div><Button className="full" onClick={() => navigate('assistant')}>调整我的 AI 助手<ChevronRight size={16}/></Button></section></div></div><div className="page-foot"><span>{w.shop.name} · {template.label}</span><span>所有数据均为演示数据</span></div></>;
}
