import { useEffect, useState } from 'react';
import { Store, House, MessageSquare, CalendarDays, Bot, Settings, RefreshCw, LogOut, Send, Upload, Plus, ShieldCheck } from 'lucide-react';
import { Button, Field, Badge, Modal, Avatar, Empty } from './components';
import { readKnowledge } from './knowledge';
import { TODAY } from './data';

async function api(route,body,method) { const res=await fetch(`/api${route}`,{credentials:'same-origin',headers:{'Content-Type':'application/json'},method:method||(body===undefined?'GET':'POST'),body:body===undefined?undefined:JSON.stringify(body)}); const data=await res.json();if(!res.ok){if(res.status===401&&route!=='/login')window.dispatchEvent(new Event('shop-session-expired'));throw new Error(data.error||'请求失败');}return data; }
const roles={OWNER:'老板',ADMIN:'店长',STAFF:'员工',CUSTOMER:'客户'};
const statuses={PENDING:'待确认',CONFIRMED:'已确认',CANCELLED:'已取消',DONE:'已完成',NO_SHOW:'未到店'};
export default function LiveApp(){
  const [auth,setAuth]=useState(null);const[page,setPage]=useState('首页');const[data,setData]=useState({contacts:[],bookings:[],logs:[]});const[status,setStatus]=useState(null);const[config,setConfig]=useState(null);const[error,setError]=useState('');const[notice,setNotice]=useState('');const[busy,setBusy]=useState(false);const[login,setLogin]=useState({username:'wa',password:''});const[selected,setSelected]=useState(null);const[messages,setMessages]=useState([]);const[text,setText]=useState('');const[question,setQuestion]=useState('');const[reply,setReply]=useState(null);const[engine,setEngine]=useState('cli');const[modal,setModal]=useState(null);const[form,setForm]=useState({});const[search,setSearch]=useState('');
  useEffect(()=>{api('/auth').then(d=>setAuth(d.authenticated)).catch(()=>setAuth(false));const expire=()=>setAuth(false);window.addEventListener('shop-session-expired',expire);return()=>window.removeEventListener('shop-session-expired',expire)},[]);
  async function refresh(){const [a,b,c]=await Promise.all([api('/overview'),api('/status'),api('/config')]);setData(a);setStatus(b);setConfig(c);}
  useEffect(()=>{if(auth)refresh().catch(e=>setError(e.message));},[auth]);
  async function run(fn,success){setBusy(true);setError('');setNotice('');try{await fn();if(success)setNotice(success);}catch(e){setError(e.message);}finally{setBusy(false);}}
  const active=data.contacts.find(c=>c.id===selected);
  async function openContact(c){setSelected(c.id);setMessages([]);setText('');await run(async()=>setMessages((await api(`/contacts/${c.id}/messages`)).messages));}
  function openModal(type){setForm(type==='person'?{name:'',phone:'',role:'CUSTOMER'}:{contactId:data.contacts[0]?.id||'',date:TODAY,time:'09:00',service:'',notes:''});setModal(type);setError('');}
  if(auth===null)return <div className="live-login"><p>正在检查登录状态…</p></div>;
  if(!auth)return <div className="live-login"><form className="panel" onSubmit={e=>{e.preventDefault();run(async()=>{await api('/login',login);setLogin({...login,password:''});setAuth(true);});}}><span className="brand-mark"><Store size={26}/></span><h1>进入你的店铺</h1><p>使用现有 Hermes WA 管理后台的用户名与密码。</p><Field label="用户名"><input autoComplete="username" required value={login.username} onChange={e=>setLogin({...login,username:e.target.value})}/></Field><Field label="密码"><input type="password" autoComplete="current-password" required value={login.password} onChange={e=>setLogin({...login,password:e.target.value})}/></Field>{error&&<p className="error">{error}</p>}<Button variant="primary" className="full" disabled={busy}>{busy?'正在登录…':'登录真实工作台'}</Button><a className="text-link" href="/" style={{marginTop:20}}>返回演示空间</a></form></div>;
  const nav=[['首页',House],['消息',MessageSquare],['预约',CalendarDays],['AI 助手',Bot],['设置',Settings]];
  return <div className="app-shell live-shell"><aside className="sidebar"><a className="brand" href="/?live=1"><span className="brand-mark"><Store size={24}/></span>小店搭子</a><div className="notice"><ShieldCheck size={18}/>真实工作台 · 仅管理员</div><nav>{nav.map(([label,Icon])=><button key={label} className={`nav-item ${page===label?'active':''}`} onClick={()=>{setPage(label);setError('');setNotice('');}}><Icon size={20}/>{label}</button>)}</nav><div className="sidebar-bottom"><a className="text-link" href="/">打开演示空间</a><Button className="full" style={{marginTop:20}} onClick={()=>run(async()=>{await api('/logout',{});setAuth(false);})}><LogOut size={16}/>退出登录</Button></div></aside><main className="main"><header className="topbar"><span>真实工作台 / {page}</span><Badge tone="green">服务端连接</Badge></header><div className="content"><div className="page-heading"><div><h1>{page}</h1><p>{page==='首页'?'真实服务、真实记录，一个地方管理。':page==='消息'?'先接管，再回复；消息会发送到 WhatsApp。':page==='AI 助手'?'发布后，资料将进入现有 WhatsApp 路由的上下文。':page==='预约'?'写入现有业务数据库，与 WhatsApp 查询共用记录。':'按电话号码管理身份权限。'}</p></div><Button disabled={busy} onClick={()=>run(refresh,'数据已刷新')}><RefreshCw size={16}/>刷新</Button></div>{error&&<div role="alert" className="error">{error}</div>}{notice&&<div role="status" className="notice">{notice}</div>}
  {page==='首页'&&<><div className="metrics">{[['联系人',data.contacts.length],['预约记录',data.bookings.length],['人工接管',data.contacts.filter(c=>!c.ai_enabled).length]].map(([k,v])=><div className="metric" key={k}><span><span className="metric-label">{k}</span><strong>{v}</strong></span></div>)}</div><div className="home-grid"><section className="panel panel-body"><h2>服务连接</h2>{[['WhatsApp',status?.waha||'检查中'],['Session',status?.session||'biz'],['Hermes API',status?.hermes?'已连接':'未连接'],['CLI-to-API',status?.modelAvailable?'Sonnet 5 可用':'检查模型配置'],['数据库',status?.database?'已连接':'未连接']].map(([k,v])=><div className="connection-row" key={k}><span>{k}</span><Badge tone={/未|检查/.test(v)?'amber':'green'}>{v}</Badge></div>)}<p className="subtle small">沿用现有 wa-router，不新增第二条消息 webhook。</p></section><section className="panel panel-body"><h2>最近操作</h2><div className="log-list">{data.logs.slice(0,8).map((l,i)=><div key={i}><span>{l.action}</span><small>{new Date(l.created_at).toLocaleTimeString('zh-CN',{timeZone:'Asia/Kuala_Lumpur'})}</small></div>)}</div></section></div></>}
  {page==='消息'&&<div className="inbox live-inbox"><aside className="conversation-list"><div className="search"><input aria-label="搜索真实客户" placeholder="搜索姓名或号码" value={search} onChange={e=>setSearch(e.target.value)}/></div>{data.contacts.filter(c=>`${c.name||''}${c.phone}`.includes(search)).map(c=><button className={`conversation-item ${selected===c.id?'selected':''}`} key={c.id} onClick={()=>openContact(c)}><Avatar name={c.name||c.phone}/><span><strong>{c.name||c.phone}</strong><small>{c.phone}</small><span className="conversation-mode">{roles[c.role]} · {c.ai_enabled?'AI 接待':'人工接管'}</span></span></button>)}</aside>{active?<section className="chat-panel"><div className="chat-header"><div><strong>{active.name||active.phone}</strong><small>{active.ai_enabled?'AI 接待中':'人工接管中'}</small></div><Button disabled={busy} onClick={()=>run(async()=>{await api(`/contacts/${active.id}/mode`,{mode:active.ai_enabled?'human':'ai'});await refresh();},active.ai_enabled?'已暂停该对话的 AI 回复':'已恢复 AI')}>{active.ai_enabled?'人工接管':'恢复 AI'}</Button></div><div className="chat-history">{messages.length?messages.slice().sort((a,b)=>a.timestamp-b.timestamp).map((m,i)=><div key={m.id||i} className={`bubble-wrap ${m.fromMe?'outgoing':'incoming'}`}><div className="bubble">{m.body||'[无文本内容]'}</div><span className="bubble-time">{m.timestamp?new Date(m.timestamp*1000).toLocaleString('zh-CN',{timeZone:'Asia/Kuala_Lumpur'}):''}</span></div>):<Empty title="没有读取到消息" text="请确认该联系人有 WhatsApp 会话，或点击刷新。"/>}</div><form className="composer" onSubmit={e=>{e.preventDefault();run(async()=>{await api(`/contacts/${active.id}/reply`,{text,requestId:crypto.randomUUID()});setText('');setMessages((await api(`/contacts/${active.id}/messages`)).messages);},'消息已发送到 WhatsApp');}}><p>{active.ai_enabled?'接管后才能发送人工回复。':'将真实发送给当前联系人，请确认收件人和内容。'}</p><div className="inline"><input aria-label="真实回复" value={text} disabled={active.ai_enabled||busy} onChange={e=>setText(e.target.value)} placeholder="输入回复…"/><Button variant="primary" disabled={active.ai_enabled||busy||!text.trim()}><Send size={16}/>发送</Button></div></form></section>:<Empty title="选择一位客户" text="查看消息和管理人工接管。"/>}</div>}
  {page==='预约'&&<section className="panel panel-body"><div className="section-heading compact"><h2>预约列表</h2><Button variant="primary" onClick={()=>openModal('booking')}><Plus size={16}/>新增预约</Button></div><p className="notice">沿用现有单店容量：每个预约预留 60 分钟。创建记录不会自动发送通知。</p>{data.bookings.length?data.bookings.map(b=><div className="service-row" key={b.id}><div><strong>{b.date} {b.time} · {b.name||b.phone}</strong><small>{b.service}</small></div><select aria-label={`预约 ${b.id} 状态`} style={{width:110}} disabled={busy} value={b.status} onChange={e=>run(async()=>{await api(`/bookings/${b.id}`,{status:e.target.value},'PATCH');await refresh();},'预约状态已保存')}>{Object.entries(statuses).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div>):<Empty title="还没有预约记录"/>}</section>}
  {page==='AI 助手'&&config&&<div className="assistant-layout"><section className="panel panel-body"><h2>身份与知识</h2><p className="subtle small" style={{margin:'8px 0 20px'}}>与演示空间分开，发布后才应用到真实业务。</p><Field label="助手名字"><input value={config.name} onChange={e=>setConfig({...config,name:e.target.value})}/></Field><Field label="身份与工作说明"><textarea rows={5} value={config.identity} onChange={e=>setConfig({...config,identity:e.target.value})}/></Field><Field label="回复语言"><select value={config.language} onChange={e=>setConfig({...config,language:e.target.value})}>{['自动匹配客户语言','中文','English','Bahasa Melayu'].map(l=><option key={l}>{l}</option>)}</select></Field><label className="upload-zone"><Upload size={24}/><strong>上传店铺资料</strong><span>PDF / DOCX / TXT / MD / CSV · 文字合计最多 8 万字</span><input type="file" accept=".pdf,.docx,.txt,.md,.csv" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)run(async()=>{const t=await readKnowledge(f);setConfig(c=>({...c,knowledge:[...c.knowledge,{id:crypto.randomUUID(),name:f.name,text:t,enabled:true}]}));},'资料已读取，发布后生效');}}/></label>{config.knowledge.map(d=><label className="toggle-row" key={d.id}><span><strong>{d.name}</strong><small>{d.text.length} 字</small></span><input aria-label={`启用 ${d.name}`} type="checkbox" checked={d.enabled} onChange={e=>setConfig({...config,knowledge:config.knowledge.map(x=>x.id===d.id?{...x,enabled:e.target.checked}:x)})}/></label>)}<details className="advanced"><summary>直接添加问答</summary><Field label="新资料内容"><textarea id="live-note" rows={3}/></Field><Button onClick={()=>{const el=document.getElementById('live-note');if(el.value.trim()){setConfig({...config,knowledge:[...config.knowledge,{id:crypto.randomUUID(),name:'手动问答',text:el.value.trim(),enabled:true}]});el.value='';}}}>加入资料</Button></details><Button variant="primary" className="full" style={{marginTop:25}} disabled={busy} onClick={()=>run(async()=>{await api('/config',config,'PUT');},'真实 AI 配置已发布，后续 WhatsApp 消息会使用新资料')}>发布到真实业务</Button></section><section className="panel panel-body"><h2>真实 AI 测试</h2><p className="notice">使用已发布资料，不向 WhatsApp 发送消息。模型：claude-sonnet-5。</p><Field label="测试通道"><select value={engine} onChange={e=>setEngine(e.target.value)}><option value="cli">CLI-to-API · Sonnet 5</option><option value="hermes">Hermes · customer 档案</option></select></Field><form onSubmit={e=>{e.preventDefault();run(async()=>setReply(await api('/test',{question,engine})));}}><Field label="测试问题"><textarea rows={4} value={question} onChange={e=>setQuestion(e.target.value)} placeholder="问问营业时间或服务价格…" required/></Field><Button variant="primary" disabled={busy}>{busy?'正在请求…':'发送测试'}</Button></form>{reply&&<div className="test-exchange" style={{marginTop:25}}><div className="test-answer">{reply.reply}</div><small className="source">{reply.engine} · {reply.model}</small></div>}</section></div>}
  {page==='设置'&&<section className="panel panel-body"><div className="section-heading compact"><h2>电话号码与身份</h2><Button onClick={()=>openModal('person')}><Plus size={16}/>添加 / 更新</Button></div><div className="notice">号码对应真实路由权限。老板和店长可以查询全店记录；请谨慎授予。</div>{data.contacts.map(c=><div className="person-row" key={c.id}><Avatar name={c.name||c.phone}/><div className="grow"><strong>{c.name||'未命名'}</strong><small>+{c.phone}</small></div><Badge tone={c.role==='OWNER'?'blue':'gray'}>{roles[c.role]}</Badge><Button variant="text" onClick={()=>{setForm({name:c.name||'',phone:c.phone,role:c.role});setModal('person');}}>编辑</Button></div>)}</section>}
  </div></main>{modal&&<Modal title={modal==='person'?'配置联系人身份':'新增真实预约'} onClose={()=>setModal(null)}><form className="modal-form" onSubmit={e=>{e.preventDefault();run(async()=>{await api(modal==='person'?'/contacts':'/bookings',form);setModal(null);await refresh();},'已保存到业务数据库');}}>{modal==='person'?<><Field label="姓名"><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="国际电话号码"><input required type="tel" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></Field><Field label="身份"><select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}>{Object.entries(roles).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></Field></>:<><Field label="客户"><select required value={form.contactId} onChange={e=>setForm({...form,contactId:e.target.value})}><option value="">请选择</option>{data.contacts.map(c=><option value={c.id} key={c.id}>{c.name||c.phone}</option>)}</select></Field><Field label="日期"><input required type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></Field><Field label="时间（马来西亚）"><input required type="time" value={form.time} onChange={e=>setForm({...form,time:e.target.value})}/></Field><Field label="服务项目"><input required value={form.service} onChange={e=>setForm({...form,service:e.target.value})}/></Field></>}{error&&<p className="error">{error}</p>}<Button variant="primary" disabled={busy}>保存</Button></form></Modal>}</div>;
}
