import { useState } from 'react';
import { Plus, ShieldCheck, Smartphone, Cable, Save, Check } from 'lucide-react';
import { templates, uid } from './data';
import { useStore } from './store';
import { Avatar, Badge, Button, Field, Modal } from './components';
export default function Settings() {
  const { workspace: w, industry, switchIndustry, update, notify } = useStore();
  const [tab, setTab] = useState('店铺'); const [shop, setShop] = useState(w.shop);
  const [person, setPerson] = useState(null); const [service, setService] = useState(null); const [error, setError] = useState('');
  return <><div className="page-heading"><div><h1>设置</h1><p>把基础设置好，日常就轻松了。</p></div></div><div className="settings-layout"><nav className="settings-nav" aria-label="设置分类">{['店铺', '服务与价格', '人员与权限', '连接', '操作记录'].map(t => <button key={t} className={tab === t ? 'active' : ''} onClick={() => setTab(t)}>{t}</button>)}</nav><section className="panel settings-content">{tab === '店铺' && <><h2>店铺资料</h2><p className="subtle">一个空间，专注经营一家店。</p><form onSubmit={e => { e.preventDefault(); update(d => { d.shop = shop; }, '更新店铺资料'); notify('店铺资料已保存'); }}><Field label="店铺名称"><input required value={shop.name} onChange={e => setShop({ ...shop, name: e.target.value })}/></Field><Field label="老板称呼"><input required value={shop.owner} onChange={e => setShop({ ...shop, owner: e.target.value })}/></Field><Field label="店铺地址"><input required value={shop.address} onChange={e => setShop({ ...shop, address: e.target.value })}/></Field><Field label="营业时间" hint="第一版按每日统一营业时间安排服务"><select value={shop.hours} onChange={e => setShop({ ...shop, hours: e.target.value })}>{['09:00–19:00', '08:00–18:00', '10:00–20:00', '10:00–22:00'].map(h => <option key={h}>{h}</option>)}</select></Field><Button variant="primary"><Save size={16}/>保存店铺资料</Button></form><div className="divider"/><h3>行业演示模板</h3><p className="subtle small">切换模板预览不同行业；各行业的演示数据独立保留。</p><div className="industry-grid">{Object.entries(templates).map(([key, t]) => <button className={industry === key ? 'selected' : ''} key={key} onClick={() => { if (key !== industry) switchIndustry(key); }}>{t.label}{industry === key && <Check size={16}/>}</button>)}</div></>}
      {tab === '服务与价格' && <><div className="section-heading compact"><div><h2>服务与价格</h2><p>AI 查询价格时，使用这里的数据。</p></div><Button onClick={() => { setService({ id: '', name: '', price: 0, duration: 60 }); setError(''); }}><Plus size={16}/>添加服务</Button></div><div className="service-list">{w.services.map(s => <button className="service-row" key={s.id} onClick={() => { setService(s); setError(''); }}><div><strong>{s.name}</strong><small>{s.duration} 分钟</small></div><span>{s.price ? `RM ${s.price}` : '免费咨询'}</span><span className="text-link">编辑</span></button>)}</div></>}
      {tab === '人员与权限' && <><div className="section-heading compact"><div><h2>人员与权限</h2><p>电话号码关联身份，消息不能改变权限。</p></div><Button onClick={() => { setPerson({ id: '', name: '', phone: '', role: '员工' }); setError(''); }}><Plus size={16}/>添加人员</Button></div><div className="notice"><ShieldCheck size={18}/><span>这里配置的是演示角色。真实登录认证和服务端权限验证将在接入阶段实现。</span></div>{w.staff.map((p, i) => <div className="person-row" key={p.id}><Avatar name={p.name} index={i}/><div className="grow"><strong>{p.name}</strong><small>{p.phone}</small></div><Badge tone={p.role === '老板' ? 'blue' : 'gray'}>{p.role}</Badge><Button variant="text" onClick={() => { setPerson(p); setError(''); }}>编辑</Button></div>)}<div className="permission-guide"><h3>默认访问范围</h3>{[['老板','全店数据、AI 配置、知识库和人员权限'],['店长','全店对话、客户和预约；不能授予老板权限'],['员工','分配给自己的对话与任务'],['客户','仅自己的对话与预约；未登记号码默认属于客户']].map(([r,t]) => <div key={r}><strong>{r}</strong><span>{t}</span></div>)}</div></>}
      {tab === '连接' && <><h2>连接你的 WhatsApp</h2><p className="subtle">让店铺消息和 AI 助手连起来。</p><div className="connection-detail"><span className="connection-icon"><Smartphone size={30}/></span><div><h3>WAHA</h3><p>WhatsApp 消息收发</p></div><Badge tone="gray">未连接</Badge></div><div className="connection-detail"><span className="connection-icon"><Cable size={28}/></span><div><h3>Hermes AI</h3><p>理解问题与执行业务操作</p></div><Badge tone="gray">未连接</Badge></div><div className="connection-note"><h3>界面已准备好，下一步接入你的服务</h3><p>当前是可交互的本地 Demo。真实接入需要 WAHA 服务地址、Session 名称和 Hermes 的调用方式。</p><p>密钥需保存在服务端，当前页面不收集或保存密钥。对话回复、预约提醒尚不会发送到 WhatsApp。</p></div></>}
      {tab === '操作记录' && <><h2>操作记录</h2><p className="subtle">仅记录此浏览器里的演示操作，最多保留 100 条。</p>{w.logs.length ? <div className="log-list">{w.logs.map(l => <div key={l.id}><i className="status-dot"/><span>{l.action}</span><small>{new Date(l.date).toLocaleString('zh-CN', { timeZone: 'Asia/Kuala_Lumpur', hour12: false })}</small></div>)}</div> : <div className="calm-empty">保存配置或处理预约后，记录会出现在这里。</div>}</>}
    </section></div>{person && <Modal title={person.id ? '编辑人员' : '添加人员'} onClose={() => setPerson(null)}><form className="modal-form" onSubmit={e => { e.preventDefault(); const phone = person.phone.replace(/[^\d+]/g, ''); if (!/^\+?\d{7,15}$/.test(phone)) return setError('请填写有效的国际电话号码。'); if (w.staff.some(p => p.id !== person.id && p.phone.replace(/[^\d+]/g, '') === phone)) return setError('这个号码已经绑定其他人员。'); if (w.staff.some(p => p.id !== person.id && p.name === person.name.trim())) return setError('人员名称不能重复。'); if (person.id === 'u1' && person.role !== '老板') return setError('店铺所有者必须保留老板身份。'); update(d => { const old = d.staff.find(p => p.id === person.id); const p = { ...person, name: person.name.trim(), phone, id: person.id || uid() }; if (old) { d.bookings.forEach(b => { if (b.staff === old.name) b.staff = p.name; }); d.staff[d.staff.findIndex(x => x.id === p.id)] = p; } else d.staff.push(p); }, `更新演示人员 · ${person.name}`); setPerson(null); notify('人员与演示权限已保存'); }}><Field label="姓名"><input required value={person.name} onChange={e => setPerson({ ...person, name: e.target.value })}/></Field><Field label="WhatsApp 电话号码"><input required type="tel" placeholder="+60123456789" value={person.phone} onChange={e => setPerson({ ...person, phone: e.target.value })}/></Field><Field label="身份"><select value={person.role} onChange={e => setPerson({ ...person, role: e.target.value })}>{['老板', '店长', '员工'].map(r => <option key={r}>{r}</option>)}</select></Field>{error && <p className="error" role="alert">{error}</p>}<Button variant="primary">保存人员</Button></form></Modal>}{service && <Modal title={service.id ? '编辑服务' : '添加服务'} onClose={() => setService(null)}><form className="modal-form" onSubmit={e => { e.preventDefault(); if (!service.name.trim()) return; update(d => { const s = { ...service, name: service.name.trim(), price: Number(service.price), duration: Number(service.duration), id: service.id || uid() }; const i = d.services.findIndex(x => x.id === s.id); if (i < 0) d.services.push(s); else d.services[i] = s; }, `更新服务 · ${service.name}`); setService(null); notify('服务已保存'); }}><Field label="服务名称"><input required value={service.name} onChange={e => setService({ ...service, name: e.target.value })}/></Field><Field label="价格（RM）"><input required type="number" min="0" step="0.01" value={service.price} onChange={e => setService({ ...service, price: e.target.value })}/></Field><Field label="服务时长（分钟）"><input required type="number" min="15" max="600" step="15" value={service.duration} onChange={e => setService({ ...service, duration: e.target.value })}/></Field><Button variant="primary">保存服务</Button></form></Modal>}</>;
}
